services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=postgres
    ports:
      - 5431:5432
    